SELECT
CPP_CATALOG.YEAR, CPP_CATALOG.QUARTER,CPP_ENROLLMENT.BRONCO_ID,CPP_STUDENTS.FIRST_NAME,
CPP_STUDENTS.LAST_NAME,CPP_STUDENTS.PHONE,CPP_STUDENTS.EMAIL,CPP_CATALOG.COURSE_ID,
CPP_COURSES.DESCRIPTION,CPP_COURSES.UNITS,CPP_INSTRUCTORS.FIRST_NAME AS INSTR_FIRST,
CPP_INSTRUCTORS.LAST_NAME AS INSTR_LAST,CPP_INSTRUCTORS.PHONE AS INSTR_PHONE,
CPP_INSTRUCTORS.DEPARTMENT FROM CPP_ENROLLMENT
 LEFT JOIN CPP_CATALOG ON CPP_ENROLLMENT.CATALOG_ID = CPP_CATALOG.CATALOG_ID
 LEFT JOIN CPP_STUDENTS ON CPP_ENROLLMENT.BRONCO_ID= CPP_STUDENTS.BRONCO_ID
 INNER JOIN CPP_COURSES ON CPP_CATALOG.COURSE_ID = CPP_COURSES.COURSE_ID
 RIGHT JOIN CPP_INSTRUCTORS ON CPP_CATALOG.PROF_ID = CPP_INSTRUCTORS.PROF_ID
ORDER BY BRONCO_ID, COURSE_ID